# Site settings
title: Allie's Adventures in Coding
header-img: img/home-bg.png
email: alliemhow@gmail.com
copyright_name: cheshicat
description: > # this means to ignore newlines until "baseurl:"
  brief excerpts from my internal monologue
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cheshicat
learn_profile: cheshicat
email_username: alliemhow@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
