# Site settings
author: Allison Howard
title: Allie's Adventures in Coding
header-img: img/home-bg.png
email: alliemhow@gmail.com
copyright_name: Allison Howard
description: > # this means to ignore newlines until "baseurl:"
  Hopefully, getting a little less lost than Alice did
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  cheshicat

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
